### ISSUE TITLE
comicR not work?

### ISSUE THREAD

**Issue by GuangchuangYu** [timelyportfolio/comicR#1]
I follow the example, but it always output html tags.

If I redirect the output to comicR, it will open an empty webpage.

If I write the output html tags as a html file as below:

``` r
library(extrafont)
library(htmltools)
library(SVGAnnotation)
library(XML)
library(ggtree)
library(gridSVG)
library(comicR)


p <- ggtree(rtree(30)) + geom_tiplab()
p
svg <- grid.export(name="")$svg
x=tagList(
      tags$div(
        id = "ggtree_comic"
        ,tags$style("#ggtree_commic text {font-family:Architects Daughter;}")
        ,tags$h3("comicR + ggtree")
        ,HTML(gsub(x=saveXML(svg),pattern="glyph", replacement="svg2-glyph"))
        ,comicR("#ggtree_example", ff=5)
      )
    )

zz=file("zz.html", "w")
writeLines(as.character(x), zz)
close(zz)
```

Opening the generated html file, it do contain the figure, but there is not comic effect.

Bests,
Guangchuang

**Comment by timelyportfolio** [comment]
The first problem I spotted is `ggtree_comic` does not match the id provided in `comicR("#ggtree_example")`.  This should be a match, or you can just leave it blank to apply to all `svg`.

```
,comicR("#ggtree_comic", ff=5)
```

If you just want to view, you can try `browsable(x)` or `html_print(x)` from `library(htmltools)`.  If you are trying to save, then `htmltools` gives us [`save_html`](http://rpackages.ianhowson.com/cran/htmltools/man/save_html.html) to help with the task.  In you example, could you try?

```
save_html( x, "zz.html" )
```

Please let me know if this solves your issue. Thanks for your work on `ggtree`.

For reference, after changing the `id`, I get this.

![image](https://cloud.githubusercontent.com/assets/837910/7633043/5da7b4c6-fa17-11e4-9f40-22259a89dc41.png)

You might notice the font is not being applied, since there is one other small error in `#ggtree_commic`.  For the full effect, this will be the code.

```
library(extrafont)
library(htmltools)
library(SVGAnnotation)
library(XML)
library(ggtree)
library(gridSVG)
library(comicR)


p <- ggtree(rtree(30)) + geom_tiplab()
p
svg <- grid.export(name="")$svg
x=tagList(
      tags$div(
        id = "ggtree_comic"
        ,tags$style("#ggtree_comic text {font-family:Architects Daughter;}")
        ,tags$h3("comicR + ggtree")
        ,HTML(gsub(x=saveXML(svg),pattern="glyph", replacement="svg2-glyph"))
        ,comicR("#ggtree_comic", ff=5)
      )
    )

```

![image](https://cloud.githubusercontent.com/assets/837910/7633133/dd3de03e-fa17-11e4-940f-03541c6835e0.png)

**Comment by GuangchuangYu** [comment]
thanks for your quick response.

**Comment by timelyportfolio** [comment]
Look forward to see what you make.  One other note is if you intend to share then you will probably also want to attach the dependency for the font Architect's Daughter, since the above example requires someone to have installed that font on their machine.  To do this, you can

```
x <- attachDependencies(
  x
  ,htmlDependency(
    name = "ArchitectsDaughter"
    ,version = "0.1"
    ,src = c(href='http://fonts.googleapis.com/css?family=Architects+Daughter')
    ,stylesheet = ""
  )
)
```

I like it better with pipes, so with `pipeR`

```
x <- x %>>%
  attachDependencies(list(
    htmlDependency(
      name = "ArchitectsDaughter"
      ,version = "0.1"
      ,src = c(href='http://fonts.googleapis.com/css?family=Architects+Daughter')
      ,stylesheet = ""
    )
  ))
```

**Comment by GuangchuangYu** [comment]
Thanks again! I test it with showtext package (https://github.com/yixuan/showtext), it seems comicR can't recognize font register by font.add of showtext. This package is more flexible to add font than extrafont.
